const std = @import("std");

const IoctlType = enum(u1) {
    get = 0,
    set = 1,
};

const IoctlStateTag = enum {
    pending,
    sent,
    done,
};

const PendingIoctl = struct {
    data: []u8,
    kind: IoctlType,
    cmd: IoctlCmd,
    iface: u32,
};

const SentIoctl = struct {
    buf: []u8,
};

const DoneIoctl = struct {
    resp_len: usize,
};

const IoctlStateInner = union(IoctlStateTag) {
    pending: PendingIoctl,
    sent: SentIoctl,
    done: DoneIoctl,
};

pub fn set_iovar_u32x2(name: []const u8, val1: u32, val2: u32) void {
    var buf: [8]u8 = undefined;
    std.mem.writeInt(u32, buf[0..], val1, .little);
    std.mem.writeInt(u32, buf[4..], val2, .little);
    set_iovar(name, buf);
}

pub fn set_iovar_u32(name: []const u8, val: u32) void {
    var buf: [4]u8 = undefined;
    std.mem.writeInt(u32, buf[0..], val, .little);
    set_iovar(name, buf);
}

pub fn set_iovar(name: []const u8, val: []u8) void {
    const IOCTL_BUFFER_SIZE = 196;
    set_iovar_v(IOCTL_BUFFER_SIZE, name, val);
}

pub fn set_iovar_v(comptime buf_size: usize, name: []const u8, val: []u8) void {
    var buf: [buf_size]u8 = undefined;
    @memcpy(buf[0..name.len], name);
    buf[name.len] = 0; // null terminated string
    @memcpy(buf[name.len + 1 .. name.len + 1 + val.len], val);

    const total_len = name.len + 1 + val.len;
    ioctl_inner(.set, .SetVar, 0, buf[0..total_len]);
}

fn ioctl_inner(kind: IoctlType, cmd: IoctlCmd, iface: u32, data: []u8) void {
    // TODO
}

const IoctlState = struct {
    const Self = @This();
    state: IoctlStateInner,

    pub fn do_ioctl(self: *Self, kind: IoctlType, cmd: IoctlCmd, iface: u32, data: []u8) void {
        self.state = IoctlStateInner{
            .pending = .{
                .kind = kind,
                .cmd = cmd,
                .iface = iface,
                .data = data,
            },
        };
    }

    pub fn ioctl_done(self: *Self, response: []u8) void {
        // TODO
    }
};

const IoctlCmd = enum(u32) {
    GetMagic = 0,
    GetVersion = 1,
    Up = 2,
    Down = 3,
    GetLoop = 4,
    SetLoop = 5,
    Dump = 6,
    GetMsglevel = 7,
    SetMsglevel = 8,
    GetPromisc = 9,
    SetPromisc = 10,
    GetRate = 12,
    GetInstance = 14,
    GetInfra = 19,
    SetInfra = 20,
    GetAuth = 21,
    SetAuth = 22,
    GetBssid = 23,
    SetBssid = 24,
    GetSsid = 25,
    SetSsid = 26,
    Restart = 27,
    GetChannel = 29,
    SetChannel = 30,
    GetSrl = 31,
    SetSrl = 32,
    GetLrl = 33,
    SetLrl = 34,
    GetPlcphdr = 35,
    SetPlcphdr = 36,
    GetRadio = 37,
    SetRadio = 38,
    GetPhytype = 39,
    DumpRate = 40,
    SetRateParams = 41,
    GetKey = 44,
    SetKey = 45,
    GetRegulatory = 46,
    SetRegulatory = 47,
    GetPassiveScan = 48,
    SetPassiveScan = 49,
    Scan = 50,
    ScanResults = 51,
    Disassoc = 52,
    Reassoc = 53,
    GetRoamTrigger = 54,
    SetRoamTrigger = 55,
    GetRoamDelta = 56,
    SetRoamDelta = 57,
    GetRoamScanPeriod = 58,
    SetRoamScanPeriod = 59,
    Evm = 60,
    GetTxant = 61,
    SetTxant = 62,
    GetAntdiv = 63,
    SetAntdiv = 64,
    GetClosed = 67,
    SetClosed = 68,
    GetMaclist = 69,
    SetMaclist = 70,
    GetRateset = 71,
    SetRateset = 72,
    Longtrain = 74,
    GetBcnprd = 75,
    SetBcnprd = 76,
    GetDtimprd = 77,
    SetDtimprd = 78,
    GetSrom = 79,
    SetSrom = 80,
    GetWepRestrict = 81,
    SetWepRestrict = 82,
    GetCountry = 83,
    SetCountry = 84,
    GetPm = 85,
    SetPm = 86,
    GetWake = 87,
    SetWake = 88,
    GetForcelink = 90,
    SetForcelink = 91,
    FreqAccuracy = 92,
    CarrierSuppress = 93,
    GetPhyreg = 94,
    SetPhyreg = 95,
    GetRadioreg = 96,
    SetRadioreg = 97,
    GetRevinfo = 98,
    GetUcantdiv = 99,
    SetUcantdiv = 100,
    RReg = 101,
    WReg = 102,
    GetMacmode = 105,
    SetMacmode = 106,
    GetMonitor = 107,
    SetMonitor = 108,
    GetGmode = 109,
    SetGmode = 110,
    GetLegacyErp = 111,
    SetLegacyErp = 112,
    GetRxAnt = 113,
    GetCurrRateset = 114,
    GetScansuppress = 115,
    SetScansuppress = 116,
    GetAp = 117,
    SetAp = 118,
    GetEapRestrict = 119,
    SetEapRestrict = 120,
    ScbAuthorize = 121,
    ScbDeauthorize = 122,
    GetWdslist = 123,
    SetWdslist = 124,
    GetAtim = 125,
    SetAtim = 126,
    GetRssi = 127,
    GetPhyantdiv = 128,
    SetPhyantdiv = 129,
    ApRxOnly = 130,
    GetTxPathPwr = 131,
    SetTxPathPwr = 132,
    GetWsec = 133,
    SetWsec = 134,
    GetPhyNoise = 135,
    GetBssInfo = 136,
    GetPktcnts = 137,
    GetLazywds = 138,
    SetLazywds = 139,
    GetBandlist = 140,
    GetBand = 141,
    SetBand = 142,
    ScbDeauthenticate = 143,
    GetShortslot = 144,
    GetShortslotOverride = 145,
    SetShortslotOverride = 146,
    GetShortslotRestrict = 147,
    SetShortslotRestrict = 148,
    GetGmodeProtection = 149,
    GetGmodeProtectionOverride = 150,
    SetGmodeProtectionOverride = 151,
    Upgrade = 152,
    GetIgnoreBcns = 155,
    SetIgnoreBcns = 156,
    GetScbTimeout = 157,
    SetScbTimeout = 158,
    GetAssoclist = 159,
    GetClk = 160,
    SetClk = 161,
    GetUp = 162,
    Out = 163,
    GetWpaAuth = 164,
    SetWpaAuth = 165,
    GetUcflags = 166,
    SetUcflags = 167,
    GetPwridx = 168,
    SetPwridx = 169,
    GetTssi = 170,
    GetSupRatesetOverride = 171,
    SetSupRatesetOverride = 172,
    GetProtectionControl = 178,
    SetProtectionControl = 179,
    GetPhylist = 180,
    EncryptStrength = 181,
    DecryptStatus = 182,
    GetKeySeq = 183,
    GetScanChannelTime = 184,
    SetScanChannelTime = 185,
    GetScanUnassocTime = 186,
    SetScanUnassocTime = 187,
    GetScanHomeTime = 188,
    SetScanHomeTime = 189,
    GetScanNprobes = 190,
    SetScanNprobes = 191,
    GetPrbRespTimeout = 192,
    SetPrbRespTimeout = 193,
    GetAtten = 194,
    SetAtten = 195,
    GetShmem = 196,
    SetShmem = 197,
    SetWsecTest = 200,
    ScbDeauthenticateForReason = 201,
    TkipCountermeasures = 202,
    GetPiomode = 203,
    SetPiomode = 204,
    SetAssocPrefer = 205,
    GetAssocPrefer = 206,
    SetRoamPrefer = 207,
    GetRoamPrefer = 208,
    SetLed = 209,
    GetLed = 210,
    GetInterferenceMode = 211,
    SetInterferenceMode = 212,
    GetChannelQa = 213,
    StartChannelQa = 214,
    GetChannelSel = 215,
    StartChannelSel = 216,
    GetValidChannels = 217,
    GetFakefrag = 218,
    SetFakefrag = 219,
    GetPwroutPercentage = 220,
    SetPwroutPercentage = 221,
    SetBadFramePreempt = 222,
    GetBadFramePreempt = 223,
    SetLeapList = 224,
    GetLeapList = 225,
    GetCwmin = 226,
    SetCwmin = 227,
    GetCwmax = 228,
    SetCwmax = 229,
    GetWet = 230,
    SetWet = 231,
    GetPub = 232,
    GetKeyPrimary = 235,
    SetKeyPrimary = 236,
    GetAciArgs = 238,
    SetAciArgs = 239,
    UnsetCallback = 240,
    SetCallback = 241,
    GetRadar = 242,
    SetRadar = 243,
    SetSpectManagment = 244,
    GetSpectManagment = 245,
    WdsGetRemoteHwaddr = 246,
    WdsGetWpaSup = 247,
    SetCsScanTimer = 248,
    GetCsScanTimer = 249,
    MeasureRequest = 250,
    Init = 251,
    SendQuiet = 252,
    Keepalive = 253,
    SendPwrConstraint = 254,
    UpgradeStatus = 255,
    CurrentPwr = 256,
    GetScanPassiveTime = 257,
    SetScanPassiveTime = 258,
    LegacyLinkBehavior = 259,
    GetChannelsInCountry = 260,
    GetCountryList = 261,
    GetVar = 262,
    SetVar = 263,
    NvramGet = 264,
    NvramSet = 265,
    NvramDump = 266,
    Reboot = 267,
    SetWsecPmk = 268,
    GetAuthMode = 269,
    SetAuthMode = 270,
    GetWakeentry = 271,
    SetWakeentry = 272,
    NdconfigItem = 273,
    Nvotpw = 274,
    Otpw = 275,
    IovBlockGet = 276,
    IovModulesGet = 277,
    SoftReset = 278,
    GetAllowMode = 279,
    SetAllowMode = 280,
    GetDesiredBssid = 281,
    SetDesiredBssid = 282,
    DisassocMyap = 283,
    GetNbands = 284,
    GetBandstates = 285,
    GetWlcBssInfo = 286,
    GetAssocInfo = 287,
    GetOidPhy = 288,
    SetOidPhy = 289,
    SetAssocTime = 290,
    GetDesiredSsid = 291,
    GetChanspec = 292,
    GetAssocState = 293,
    SetPhyState = 294,
    GetScanPending = 295,
    GetScanreqPending = 296,
    GetPrevRoamReason = 297,
    SetPrevRoamReason = 298,
    GetBandstatesPi = 299,
    GetPhyState = 300,
    GetBssWpaRsn = 301,
    GetBssWpa2Rsn = 302,
    GetBssBcnTs = 303,
    GetIntDisassoc = 304,
    SetNumPeers = 305,
    GetNumBss = 306,
    GetWsecPmk = 318,
    GetRandomBytes = 319,
};
